config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    get "signin", to: "users/sessions#new"
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:new, :create, :show] do
    collection do
      get :likes
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :cares, only: [:index, :show]
  get "cares/owner/:id", to: "cares#owner", as: "care_owner"
  post "cares/owner/:id/reviews", to: "reviews#create", as: "reviews"
  delete "cares/owner/:id/reviews/:id", to: "reviews#destroy", as: "review"
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/cares_controller.rb
class CaresController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.includes([:profile]).page(params[:page]).per(12)
    @count = Post.all.count
    @like = Like.new
  end

  def show
    @post = Post.find(params[:id])
    if @post.start == @post.finish
      @day = 1
    else
      @day = ((@post.finish - @post.start) + 1).to_int
    end
  end

  def owner
    @user = User.find(params[:id])
    @owner = @user.profile
    @review = Review.new
    @reviews = Review.where(user_id: @user.id).includes(:contributor).order(created_at: :desc)
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |u|
          if cu.room_id == u.room_id
            @is_room = true
            @room_id = cu.room_id
          end
        end
      end

      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end
end

app/views/cares/_no_seach.html.erb
<% posts.each do |p| %>
<div class="cares-request-container-card">
  <div class="cares-request-container-post">
    <%= link_to care_path(p), class: "cares-request-container-post-link" do %>
      <div class="cares-request-container-post-link-box">
        <%= image_tag p.profile.image.url(:icon), class: "cares-request-container-post-link-box-image" %>
      </div>
      <div class="cares-request-container-post-link-profile">
        <div class="cares-request-container-post-link-profile-top">
          <%= p.profile.cat_name %>
        </div>
        <div class="cares-request-container-post-link-profile-bottom">
          <%= p.profile.age %> / <%= p.profile.address %>
        </div>
      </div>
      <div class="cares-request-container-post-link-feature">
        <p class="cares-request-container-post-link-feature-text"><%= p.feature %></p>
      </div>
    <% end %>
  </div>
  <div id="likes_buttons_<%= p.id %>" class="cares-request-container-post-like">
    <%= render "likes/like", p: p %>
  </div>
</div>
<% end %>

app/views/cares/_search.html.erb
<% search_posts.each do |p| %>
<div class="cares-request-container-card">
  <div class="cares-request-container-post">
    <%= link_to care_path(p), class: "cares-request-container-post-link" do %>
      <div class="cares-request-container-post-link-box">
        <%= image_tag p.profile.image.url(:icon), class: "cares-request-container-post-link-box-image" %>
      </div>
      <div class="cares-request-container-post-link-profile">
        <div class="cares-request-container-post-link-profile-top">
          <%= p.profile.cat_name %>
        </div>
        <div class="cares-request-container-post-link-profile-bottom">
          <%= p.profile.age %> / <%= p.profile.address %>
        </div>
      </div>
      <div class="cares-request-container-post-link-feature">
        <p class="cares-request-container-post-link-feature-text"><%= p.feature %></p>
      </div>
    <% end %>
  </div>
  <div id="likes_buttons_<%= p.id %>" class="cares-request-container-post-like">
    <%= render "likes/like", p: p %>
  </div>
</div>
<% end %>

app/views/cares/index.html.erb
<% content_for(:page_title) {"猫ちゃんのお世話依頼"} %>
<div class="cares-request-wrapper">
  <h2 class="cares-request-title">猫ちゃんのお世話依頼</h2>
  <% if @count.blank? %>
    <p class="cares-request-count">全 <span><%= @count %></span> 件の依頼が来てるにゃ！</p>
  <% else %>
    <p class="cares-request-count">全 <span><%= @search_count %></span> 件の依頼が来てるにゃ！</p>
  <% end %>
  <% if @search_count == 0 %>
    <p class="no-hit">検索結果がヒットしなかったにゃ</p>
  <% else %>
    <% if @search_posts %>
    <div class="cares-request-container">
      <%= render "cares/search", search_posts: @search_posts %>
    </div>
    <%= paginate @search_posts %>
    <% else %>
    <div class="cares-request-container">
      <%= render "cares/no_search", posts: @posts %>
    </div>
    <%= paginate @posts %>
    <% end %>
  <% end %>
</div>

app/views/cares/owner.html.erb
<% content_for(:page_title) {"#{@owner.user_name}さんのマイページ"} %>
<div class="owner">
  <h2 class="owner-title"><%= @owner.user_name %>さんのマイページ</h2>
  <div class="owner-wrapper">
    <div class="owner-profile">
      <div class="owner-profile-top">
        <div class="owner-profile-top-image">
          <%= image_tag @owner.image.url(:icon), class: "owner-cat", alt: "猫のアイコン" %>
        </div>
        <div class="owner-profile-top-cat">
          <h3 class="owner-profile-top-cat-list"><%= @owner.cat_name %></h3>
          <h3 class="owner-profile-top-cat-list"><%= @owner.address %></h3>
        </div>
      </div>
      <div class="owner-profile-bottom">
        <h4 class="owner-profile-bottom-user">飼い主さん : <%= @owner.user_name %></h4>
        <div class="owner-profile-bottom-introduction">
          <h3 class="owner-profile-bottom-introduction-title">自己紹介</h3>
          <p class="owner-profile-bottom-introduction-text"><%= safe_join(@owner.introduction.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
    <ul class="owner-link">
      <li class="owner-link-list"><%= link_to "依頼詳細ページに戻る", :back, class: "transition-link" %></li>
      <% unless @user.id == current_user.id %>
      <% if @is_room == true %>
        <li class="owner-link-message-come"><%= link_to "トークルームに行く", room_path(@room_id), class: "owner-link-message-come-btn" %></li>
      <% else %>
        <%= form_for @room do |f| %>
          <%= fields_for @entry do |e| %>
            <%= e.hidden_field :user_id, :value=> @user.id %>
          <% end %>
          <li class="owner-link-message-start"><%= f.submit "メッセージを始める", class: "owner-link-message-start-btn" %></li>
        <% end %>
      <% end %>
    <% end %>
    </ul>
  </div>
  <% if user_signed_in? %>
    <div class="reivew-create">
      <p class="reivew-create-title">レビューを投稿する</p>
      <%= render partial: 'reviews/form', locals: { review: @review, user: @user } %>
    </div>
  <% end %>
  <hr>
  <div class="reviews-wrapper">
    <%= render partial: 'reviews/index', locals: { reviews: @reviews } %>
  </div>
</div>

app/views/cares/show.html.erb
<% content_for(:page_title) {"#{@post.profile.cat_name}の依頼詳細ページ"} %>
<div class="cares-wrapper">
  <h2 class="cares-title"><%= @post.profile.cat_name %>の依頼詳細ページ</h2>
  <div class="cares-container">
    <div class="cares-container-image">
      <div class="cares-container-image-box">
        <%= image_tag @post.profile.image.url %>
      </div>
      <div class="cares-container-image-text">
        <div class="cares-container-image-text-top">
          <p class="cares-container-image-text-top-name"><%= @post.profile.cat_name %></p>
        </div>
        <div class="cares-container-image-text-bottom">
          <p class="cares-container-image-text-bottom-age"><%= @post.profile.age %> /</p>
          <p class="cares-container-image-text-bottom-address"><%= @post.profile.address %></p>
        </div>
      </div>
    </div>
    <div class="cares-container-user">飼い主さん :
    <% if current_user.id == @post.user_id %>
      <%= link_to @post.profile.user_name, user_path(current_user), class: "cares-container-user-link" %>
    <% else %>
      <%= link_to @post.profile.user_name, care_owner_path(@post.user.id), class: "cares-container-user-link" %>
    <% end %>
    </div>
    <div class="cares-container-plan">
      <h3 class="cares-container-plan-title"><span>■</span>希望のお世話時期と場所</h3>
      <table class="cares-container-plan-tables">
        <tbody class="cares-container-plan-tables-contents">
          <tr class="cares-container-plan-tables-contents-inner">
            <td class="cares-container-plan-tables-contents-inner-subject">お世話時期</td>
            <td class="cares-container-plan-tables-contents-inner-text"><%= @post.start.strftime("%m月%d日") %>〜<%= @post.finish.strftime("%m月%d日") %></td>
          </tr>
          <tr class="cares-container-plan-tables-contents-inner">
            <td class="cares-container-plan-tables-contents-inner-subject">お世話日数</td>
            <td class="cares-container-plan-tables-contents-inner-text"><%= @day %>日間</td>
          </tr>
          <tr class="cares-container-plan-tables-contents-inner">
            <td class="cares-container-plan-tables-contents-inner-subject">お世話場所</td>
            <td class="cares-container-plan-tables-contents-inner-text"><%= @post.place %></td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="cares-container-feature">
      <h3 class="cares-container-feature-title"><span>■</span>特徴</h3>
      <div class="cares-container-feature-textarea">
        <p class="cares-container-feature-textarea-content"><%= safe_join(@post.feature.split("\n"),tag(:br)) %></p>
      </div>
    </div>
    <% if current_user.id == @post.user_id %>
      <%= link_to "飼い主さんのマイページ", user_path(current_user), class: "back-cares-link" %></li>
      <%= link_to "編集する", edit_post_path(@post), class: "back-cares-link" %></li>
    <% else %>
      <%= link_to "飼い主さんのマイページ", care_owner_path(@post.user.id), class: "back-cares-link" %></li>
    <% end %>
    <%= link_to "お世話依頼に戻る", cares_path, class: "back-cares-link" %></li>
    </ul>
  </div>
</div>