config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    get "signin", to: "users/sessions#new"
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:new, :create, :show] do
    collection do
      get :likes
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :cares, only: [:index, :show]
  get "cares/owner/:id", to: "cares#owner", as: "care_owner"
  post "cares/owner/:id/reviews", to: "reviews#create", as: "reviews"
  delete "cares/owner/:id/reviews/:id", to: "reviews#destroy", as: "review"
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, length: { in: 6..128 }, format: { with: VALID_EMAIL_REGEX }, allow_nil: true

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end
  has_many :reviews, foreign_key: :contributor_id, dependent: :destroy
  has_many :entries
  has_many :direct_messages
  has_many :rooms, through: :entries
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: [:update, :destroy]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_profile_path
  end

  def after_update_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path
      flash[:alert] = "ゲストユーザーの更新・削除はできないにゃ"
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path
    flash[:notice] = "ゲストユーザーとしてログインしたにゃ！"
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def likes
    @likes = current_user.liked_posts.includes([:profile]).page(params[:page]).per(12)
    @count = current_user.liked_posts.count
    @like = Like.new
  end

  def show
    @profile = current_user.profile
    @reviews = Review.where(user_id: current_user.id).includes(:contributor).order(created_at: :desc)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/likes.html.erb
<% content_for(:page_title) {"気ににゃるリスト"} %>
<div class="cares-likes-wrapper">
  <h2 class="cares-likes-title">気ににゃるリスト</h2>
  <p class="cares-likes-count">全 <span><%= @count %></span> 件 気ににゃっているにゃ！</p>
    <% if @count == 0 %>
      <p class="no-hit">まだ気ににゃる依頼はないにゃ</p>
    <% else %>
      <div class="cares-likes-container">
        <% @likes.each do |like| %>
          <div class="cares-likes-container-card">
            <div class="cares-likes-container-post">
              <%= link_to care_path(like), class: "cares-likes-container-post-link" do %>
                <div class="cares-likes-container-post-link-box">
                  <%= image_tag like.profile.image.url(:icon), class: "cares-likes-container-post-link-box-image" %>
                </div>
                <div class="cares-likes-container-post-link-profile">
                  <div class="cares-likes-container-post-link-profile-top">
                    <%= like.profile.cat_name %>
                  </div>
                  <div class="cares-likes-container-post-link-profile-bottom">
                    <%= like.profile.age %> / <%= like.profile.address %>
                  </div>
                </div>
                <div class="cares-likes-container-post-link-feature">
                  <p class="cares-likes-container-post-link-feature-text">
                    <%= like.feature %>
                  </p>
                </div>
              <% end %>
            </div>
            <div id="likes_buttons_<%= like.id %>" class="cares-likes-container-post-like">
              <%= render "likes/like", like: like %>
            </div>
          </div>
        <% end %>
      </div>
      <%= paginate @likes %>
    <% end %>
  <div class="back-mypage">
    <%= link_to "マイページに戻る", user_path(current_user), class: "back-mypage-link" %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for(:page_title) {"マイページ"} %>
<div class="mypage">
  <h2 class="mypage-title">マイページ</h2>
  <div class="mypage-wrapper">
    <div class="mypage-profile">
      <div class="mypage-profile-top">
        <div class="mypage-profile-top-image">
          <%= image_tag current_user.profile.image.url(:icon), class: "mypage-cat", alt: "猫のアイコン" %>
        </div>
        <div class="mypage-profile-top-cat">
          <h3 class="mypage-profile-top-cat-list"><%= current_user.profile.cat_name %></h3>
          <h3 class="mypage-profile-top-cat-list"><%= current_user.profile.address %></h3>
        </div>
      </div>
      <div class="mypage-profile-bottom">
        <h4 class="mypage-profile-bottom-user">飼い主さん : <%= current_user.profile.user_name %></h4>
        <div class="mypage-profile-bottom-introduction">
          <h3 class="mypage-profile-bottom-introduction-title">自己紹介</h3>
          <p class="mypage-profile-bottom-introduction-text"><%= safe_join(current_user.profile.introduction.split("\n"),tag(:br)) %></p>
        </div>
      </div>
    </div>
    <ul class="mypage-link">
      <li class="mypage-link-list"><%= link_to "プロフィールを編集する", edit_profile_path(@profile.id), class: "transition-link" %></li>
      <li class="mypage-link-list"><%= link_to "気ににゃるリスト", likes_users_path, class: "transition-link" %></li>
      <li class="mypage-link-list"><%= link_to "依頼登録履歴", posts_path, class: "transition-link" %></li>
    </ul>
  </div>
  <hr>
  <div class="reviews-wrapper">
    <p class="review-title">あなたへのレビュー (<%= @reviews.count %>)</p>
    <% if @reviews.blank? %>
      <p class="no-review">まだレビューは投稿されてないにゃ</p>
    <% end %>
    <% @reviews.each do |review| %>
      <% unless review.id.nil? %>
        <li class="review-container">
          <div class="review-box">
            <div class="review-avatar">
              <%= image_tag review.contributor.profile.image.url(:mini), class: "review-image", alt: "猫のアイコン" %>
              <%= link_to "#{review.contributor.profile.user_name}", care_owner_path(review.contributor.id), class: "review-avatar-link" %>
            </div>
            <div class="review-date pull-right">
              <%= review.created_at.strftime('%m/%d %H:%M') %>
            </div>
          </div>
          <div class="review-content">
            <%= safe_join(review.content.split("\n"),tag(:br)) %>
          </div>
        </li>
      <% end %>
    <% end %>
  </div>
</div>