config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    get "signin", to: "users/sessions#new"
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:new, :create, :show] do
    collection do
      get :likes
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :cares, only: [:index, :show]
  get "cares/owner/:id", to: "cares#owner", as: "care_owner"
  post "cares/owner/:id/reviews", to: "reviews#create", as: "reviews"
  delete "cares/owner/:id/reviews/:id", to: "reviews#destroy", as: "review"
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<div class="home">
  <div class="home-cover">
    <div class="logo-area">
      <%= image_tag "large-logo.png", class: "large-logo-img", alt: "ロゴ画像" %>
    </div>
    <ul class="btn-box">
      <li class="btn-list">
        <%= link_to "ログイン", signin_path, class: "btn btn-primary large-btn" %>
      </li>
      <li class="btn-list">
        <%= link_to "会員登録", signup_path, class: "btn btn-success large-btn" %>
      </li>
    </ul>
    <div class="guest-login">
      <% unless user_signed_in? %>
        <%= link_to "ゲストでログイン", guest_sign_in_path, method: :post, class: "guest-login-text" %>
      <% end %>
    </div>
  </div>
  <div class="home-contents">
    <h1 class="home-contents-title">
      <span>NyanLeave<span> とは？
    </h1>
    <div class="home-contents-main">
      <p class="home-contents-main-text">
        NyanLeaveは、飼っている猫ちゃんを預ける・お世話することができるペットシッターマッチングサービスです。<br><br>
        旅行や出張などで、家でお留守番している猫ちゃんを、代わりにお世話をしてくれる人に依頼することができます。反対に、お世話することもできます。お互いの猫を自分の飼い猫のように想い合える、優しい関係を築きます。<br><br>
        長期間家を空けると、「おなかすいてるかな」「トイレはちゃんとできたかな」「寂しくないかな」などの心配事はいくつも浮かびますよね。私も何度もそのような体験をしたので、安心して猫ちゃんがお留守番できるよう、気軽に依頼することが出来るサービスを作りました。<br><br>
        お互いに大変な時は助け合い、猫と猫、人と人との繋がりを大切に、猫活をシェアしていきましょう。
      </p>
      <div class="home-contents-main-image">
        <%= image_tag "cat-image.jpg", class: "cat-image", alt: "猫の画像" %>
      </div>
    </div>
  </div>
</div>