config/routes.rb
Rails.application.routes.draw do
  root "home#home"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
  }

  devise_scope :user do
    get "signup", to: "users/registrations#new"
    get "signin", to: "users/sessions#new"
    post 'guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:new, :create, :show] do
    collection do
      get :likes
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  resources :posts do
    resource :likes, only: [:create, :destroy]
  end
  resources :cares, only: [:index, :show]
  get "cares/owner/:id", to: "cares#owner", as: "care_owner"
  post "cares/owner/:id/reviews", to: "reviews#create", as: "reviews"
  delete "cares/owner/:id/reviews/:id", to: "reviews#destroy", as: "review"
  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @user = User.find(params[:id])
    @review = @user.reviews.build(review_params)
    if @review.save
      redirect_back(fallback_location: root_path)
      flash[:notice] = "レビューを投稿したにゃ！"
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "レビューを入力してにゃ"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_back(fallback_location: root_path)
    flash[:notice] = "レビューを削除したにゃ！"
  end

  private

  def review_params
    params.require(:review).permit(:content).merge(user_id: @user.id, contributor_id: current_user.id)
  end
end

app/views/reviews/_form.html.erb
<%= form_with(model: [user, review], url: reviews_path(@user)) do |f| %>
  <%= f.text_area :content, placeholder: "この人への感想を書くにゃ！", class: "review-form" %>
  <%= f.submit "送信", class: "review-btn" %>
<% end %>

app/views/reviews/_index.html.erb
<p class="review-title">レビュー (<%= reviews.count %>)</p>
<% if reviews.blank? %>
  <p class="no-review">まだレビューは投稿されてないにゃ</p>
<% end %>
<% reviews.each do |review| %>
  <% unless review.id.nil? %>
    <li class="review-container">
      <div class="review-box">
        <div class="review-avatar">
          <%= image_tag review.contributor.profile.image.url(:mini), class: "review-image", alt: "猫のアイコン" %>
          <% if review.contributor == current_user %>
            <%= link_to "#{review.contributor.profile.user_name}", user_path(current_user), class: "review-avatar-link" %>
          <% else %>
            <%= link_to "#{review.contributor.profile.user_name}", care_owner_path(review.contributor.id), class: "review-avatar-link" %>
          <% end %>
        </div>
        <div class="review-option">
          <div class="review-entry">
            <% if review.contributor == current_user %>
              <%= link_to review_path(review.contributor_id, review.id), data: { confirm: "投稿を削除するかにゃ？", cancel: "やめる", commit: "削除する", title: "確認", method: :delete }, class: "review-destroy" do %>
                <p>削除</p>
              <% end %>
            <% end %>
          </div>
          <div class="review-date pull-right">
            <%= review.created_at.strftime('%m/%d %H:%M') %>
          </div>
        </div>
      </div>
      <div class="review-content">
        <%= safe_join(review.content.split("\n"),tag(:br)) %>
      </div>
    </li>
  <% end %>
<% end %>